### ISSUE TITLE
Variables driver

### ISSUE THREAD

**Issue by kjeldflarup** [labgrid-project/labgrid#1057]
I would like to make a driver which can support arbitrary information from a remote place. 

Ex in exporter.yaml I write:
```
  Variables:
    gw: '192.168.19.1'
```
The idea is that I can define any variables in this section. Instead of writing new driver, I can then query the Variables for the values I need.

Then I add Variables ressource and a VariablesDriver. But it seems that I must add a binding for all allowed variable names! And that is exactly what I want to avoid.

Any ideas how to write this VariablesDriver?

**Comment by Emantor** [comment]
What is the exact use case for this? Would attaching information to the place be sufficient? We already have the tags information there which can't be retrieved from the `RemotePlace` yet, but that could be fixed.

**Comment by kjeldflarup** [comment]
- One example is the one show. When doing a factory reset of the target, I need to set the IP configuration again, but NetworkService only supplies an ip address.
- I need to reconfigure the switchport in the Cisco switch for some tests. I then would need to know which switch and port the target is connected to. 
- I have a ftdi device, which I need the serial number of.


Lots of small issues which does not justify writing a new driver each time.

**Comment by kjeldflarup** [comment]
It could be a possibility to add options: in exporter.yaml just like labgrid.yaml has options:

**Comment by jluebbe** [comment]
In the environment YAML, you can set features (per target and globally) and options (globally):
https://labgrid.readthedocs.io/en/latest/configuration.html#environment-configuration

As @Emantor said, we already have tags on places in the coordinator, which are basically key-value-pairs.
It should be easy to expose them as a `tags` dictionary on the RemotePlace resource.

> * I have a ftdi device, which I need the serial number of.

This is at the resource level and can already be done using matches:
```
   example-group:
     location: example-location
     USBSerialPort:
       match:
         ID_SERIAL_SHORT: ID23421JLK
```

**Comment by kjeldflarup** [comment]
How can I add tags to the exporter yaml file. Or do I need to script that? 

And then I need to have the tags added to RemotePlace. I assume that it is a bit more complicated that writing 
```
tags = attr.ib(validator=attr.validators.optional(attr.validators.instance_of(str)))
```

And no, it is not just to identify a serial device I need to access the FTDI, I also need to program some GPIO's on it.

**Comment by jluebbe** [comment]
> How can I add tags to the exporter yaml file. Or do I need to script that?

It's not in the exporter, but on the coordinator. They can be set using `labgrid-client set-tags`: https://labgrid.readthedocs.io/en/latest/usage.html#place-scheduling

> And then I need to have the tags added to RemotePlace. I assume that it is a bit more complicated that writing
> 
> ```
> tags = attr.ib(validator=attr.validators.optional(attr.validators.instance_of(str)))
> ```

It should be a dictionary: `attr.ib(default=attr.Factory(dict), validator=attr.validators.instance_of(dict))`. Then you need to get the tags from the coordinator and store them on the RemotePlace in `labgrid/resource/remote.py:on_resource_added()`.

> And no, it is not just to identify a serial device I need to access the FTDI, I also need to program some GPIO's on it.

Doesn't GPIO access conflict with using the serial port? Or do you have different devices for that?

**Comment by kjeldflarup** [comment]
> It's not in the exporter, but on the coordinator. They can be set using labgrid-client set-tags: https://labgrid.readthedocs.io/en/latest/usage.html#place-scheduling

This perhaps illustrates one problem with using tags, that tags is intended for scheduling and not options. 

All the information I have in the coordinator, comes from the exporter yaml file. Thus the only difference for all my targets is the yaml file. This becomes a bit trickier using tags.

For now I put my options as comments in the yaml file, and parses them to apply the tags.

And in conftest.py I have added this fixture
```
@pytest.fixture(scope='session')
def remote_tags():
    output = subprocess.run(["labgrid-client", "show"],capture_output=True)
    assert output.returncode == 0

    tags = {}
    for line in output.stdout.decode('ascii').split('\n'):
        if 'tags:' in line:
            matches = re.findall( r'\w+=\w+', line)
            for m in matches:
                s = m.split('=')
                tags[s[0]] = s[1]
    return tags

```

> Doesn't GPIO access conflict with using the serial port? Or do you have different devices for that?
I'm not into the details of the design of the debug print we use, but it has 4 serial ports and a number of GPIO's that I can use.

**Comment by Bastian-Krause** [comment]
I think #1202 should solve this. If there's anything else open, please speak up.
