### ISSUE TITLE
Getting remote exit code from ssh command using labgrid-client

### ISSUE THREAD

**Issue by kjeldflarup** [labgrid-project/labgrid#1063]
I execute this from a shell script
```
$ labgrid-client ssh notfound
bash: line 1: notfound: command not found
connection lost (remote exit code 127)
$ echo $?
0
```
I had expected that I would get the remote exit code, but I don't.  
How can I get the remote exit code?

**Comment by Bastian-Krause** [comment]
Yes, you should get the remote exit code. It's a bug. Since it's similar to #660, I've added it there.
