### ISSUE TITLE
Add copy/write-files command to labgrid client

### ISSUE THREAD

**Issue by Emantor** [labgrid-project/labgrid#1076]
We currently only allow full disk updates using labgrid client, however for development it's often useful to replace only a folder or binary on the disk. For this we had #548 and #820 which used `pmount`. However we don't see `pmount` as the correct solution for mounting devices, rather `udisks2` should be used to mount the device and the requirement for exporters needs to be documented. List
- [ ] implement write-file via `udisks` mounting
- [ ] document exporter requirement

**Comment by a3f** [comment]
Implementation at https://github.com/labgrid-project/labgrid/pull/1219.

**Comment by Emantor** [comment]
Yes, thanks.
