### ISSUE TITLE
labgrid-suggest doesn't notice new fastboot devices

### ISSUE THREAD

**Issue by khilman** [labgrid-project/labgrid#1086]
labgrid-suggest is a great tool when adding new devices, and it works great for USB serial ports etc.  But it doesn't detect new USB fastboot devices.  

Please consider it a feature request to add detection/report of fastboot devices to labgrid-suggest.  At least ones that are using the standard USB vendor/device IDs from google for this.

**Comment by jluebbe** [comment]
Devices with vendor 1D6B and model 0104 should work already. Could you post the output of `udevadm monitor -p` when connecting the device that is not detected?

**Comment by khilman** [comment]
This one has a different vendor ID:
```
$ lsusb |grep -i google
Bus 001 Device 068: ID 18d1:fada Google Inc. USB download gadget
```

Also, here is the `udevadm monitor -p ` output when the device is plugged in:

[fastboot.log](https://github.com/labgrid-project/labgrid/files/10559750/fastboot.log)

**Comment by khilman** [comment]
I just noticed `adb_user=yes` in the monitor output.  Perhaps combining this with `ID_VENDOR_FROM_DATABASE=Google Inc.` would be enough info to decide this is an adb/fastboot device instead of relying on keeping a list of diffferent `ID_MODEL_ID` ?

**Comment by Emantor** [comment]
This will work with distros that use  [android-udev-rules](https://github.com/M0Rf30/android-udev-rules), which includes at least NixOS and Arch Linux, but not debian (or I am bad at searching).

**Comment by Emantor** [comment]
The problem with this is that we not only identify fastboot devices, but also devices which only have `adb` enabled.

**Comment by jluebbe** [comment]
As long as we don't have a ADBDriver, matching on adb_user=yes is probably fine.

When we add ADB support, we'll need to distinguish between them somehow, as otherwise both resources will become available at the same time, which is makes it harder to synchronize with target state changes.
