### ISSUE TITLE
Smart acquire and release features

### ISSUE THREAD

**Issue by kjeldflarup** [labgrid-project/labgrid#1183]
For a while I have been thinking about adding some options to labgrid-client.  
My use case is that in my CI I have implemented a power off in the teardown.  
This means that I need to power on the targets whenever I want to access them, as well as ssh access is neither possible.

Thus I would like to be able to write:

```
labgrid-client -p PLACE -a -o console
```

-a Acquired the PLACE  
-o Executes a power on
 
I would then also implement automatic release, as it typically happens that targets are acquired manually.

-A Acquires the PLACE, and releases it again on exit.  
-O Powers on, and powers off on exit

Where is the best place to add these extra steps.

**Comment by Emantor** [comment]
I don't think this should be added to labgrid itself, you can write your own shell wrapper for this, something like
```sh
labgrid-client() {
  labgrid-client lock;
  labgrid-client power on;
  labgrid-client $1;
  labgrid-client power off;
  labgrid-client unlock;
}
```
and the place can be set using the `LG_PLACE` variable.
