### ISSUE TITLE
docs: WARNING: autodoc: failed to import module 'eaton' from module ...

### ISSUE THREAD

**Issue by sjg20** [labgrid-project/labgrid#1352]
I am seeing warnings when building the docs:

```
cd doc
make html
...
WARNING: autodoc: failed to import module 'eaton' from module 'labgrid.driver.power'; the following exception was raised:
No module named 'pysnmp'
WARNING: autodoc: failed to import module 'poe_mib' from module 'labgrid.driver.power'; the following exception was raised:
No module named 'pysnmp'
WARNING: autodoc: failed to import module 'raritan' from module 'labgrid.driver.power'; the following exception was raised:
No module named 'pysnmp'
WARNING: autodoc: failed to import module 'siglent' from module 'labgrid.driver.power'; the following exception was raised:
No module named 'vxi11'
WARNING: autodoc: failed to import module 'tplink' from module 'labgrid.driver.power'; the following exception was raised:
No module named 'kasa'
WARNING: autodoc: failed to import module 'snmp' from module 'labgrid.util'; the following exception was raised:
No module named 'pysnmp'
```

**Comment by Emantor** [comment]
Looks like we have a whole bunch of modules which were never added to the pyproject.toml file but are required for automatic doc generation. We'll need to check whether they are required or if the warnings can be safely ignored.

**Comment by Bastian-Krause** [comment]
> Looks like we have a whole bunch of modules which were never added to the pyproject.toml file but are required for automatic doc generation. We'll need to check whether they are required or if the warnings can be safely ignored.

Huh? All these modules are referenced in the pyproject.toml in the "dev" extra.

@sjg20 If you want to have autodoc functionality, follow the [steps in the docs](https://labgrid.readthedocs.io/en/latest/development.html#building-the-documentation ), but use `pip install -e ".[dev]"` instead of `pip install -e ".[doc]"`. A PR adding this to this docs section would be appreciated :)

**Comment by sjg20** [comment]
OK, will do. I also hit this problem:

https://github.com/readthedocs/readthedocs.org/issues/9038

Python seems to be a disaster at the moment
