### ISSUE TITLE
Remote NetworkPowerPort

### ISSUE THREAD

**Issue by aparcar** [labgrid-project/labgrid#1413]
Hi, I defined a NetworkPowerPort which is exported to the coordinator. I'd expect that the client tells the exporter to perform certain actions like power cycle the device, however it seem that the client tries to directly access the host defined in NetworkPowerPort.

Is this intentional? This behavior would require that every client has full access to the network of an exporter, instead of a subset of commands defined by labgrid itself?

**Comment by Emantor** [comment]
Yeah, the network power ports a a bit special since many support network access. The exporter can proxy the connection though, if you start it with the `--isolated` command line argument.
