### ISSUE TITLE
Dockers files

### ISSUE THREAD

**Issue by krevsbech** [labgrid-project/labgrid#142]
**Proposal:**
I've created a docker file to setup a coordinator in a container and one to run a labgrid-client/execute the tests. 
Are you interested in these, and if yes. Should i create a PR adding the folder docker to the labgrid repository, or are you more up for a separate repository inside the project ?

**Comment by Emantor** [comment]
We are definitely interested, I would prefer a separate repository in the project.

**Comment by krevsbech** [comment]
Perfect 
I've pushed to my own space for now as I don't think i have the permissions to create a repository in your project. Will you create a repository that I can put a PR in, or clone: https://github.com/krevsbech/labgrid-docker-images

**Comment by krevsbech** [comment]
@Emantor Will you crate a repo in the project space, then I will make a PR with the docker files?

**Comment by Emantor** [comment]
There is https://github.com/labgrid-project/labgrid-docker-images now, please submit your PR there, sorry for the wait.

**Comment by krevsbech** [comment]
No problem.
Can you please create an empty Master branch with e.g. a readme, as I am not allowed to open a pull request where there is no branch.

**Comment by jluebbe** [comment]
I've deleted the empty repo and forked your labgrid-docker-images instead. You should now be able to open PRs.

**Comment by krevsbech** [comment]
@jluebbe  Perfect
If you are interested I would be happy to help asses incoming pull request, on the docker repo.
