### ISSUE TITLE
Missing binary labgrid-coordinator from pip version 24.0.2

### ISSUE THREAD

**Issue by fcervigni-EP** [labgrid-project/labgrid#1537]
Hi, 

thank you for your work.

### context

* Ubuntu 22.04
* Installing via python virtual environment, as of docs
* tested today as of **5 Nov 2024**

I installed with venv, as of today 5 Nov 2024.

### installation steps

```shell
python3 -m venv labgrid-venv
. labgrid-venv/bin/activate
pip install --upgrade pip
pip install labgrid
```

### installation result

I obtain version 24.0.2

```shell
> pip show labgrid
Name: labgrid
Version: 24.0.2
```

### issue

Binary **labgrid-coordinator is not available**

```shell
> labgrid-<TAB>
labgrid-autoinstall  labgrid-client       labgrid-exporter     labgrid-suggest   
```

Thank you in advance for any info.

**Comment by Bastian-Krause** [comment]
Hi, please use the corresponding versions of the docs for v24.0.2: https://labgrid.readthedocs.io/en/v24.0.2/. labgrid-coordinator is only installed into $PATH on master.
