### ISSUE TITLE
Entering kernel is not detected by driver

### ISSUE THREAD

**Issue by GOMSPACEMartin** [labgrid-project/labgrid#184]
I have a pytest that fails during verification of kernel present. Looking at the 'ubootdriver.py' it looks like that the verification is depended on writing Linux version upon kernel boot.

Is there any way to configure this detection method as  my Linux version 4.9.0-adi does not show this upon entering the kernel.

`    @Driver.check_active
    @step()
def await_boot(self):
        """Wait for the initial Linux version string to verify we succesfully
        jumped into the kernel.
        """
        self.console.expect(r"Linux version \d")`

Also with multiple kernels on different targets I would like to be able to detect the correct kernels etc. as part of the driver.

Currently this is blocking all my tests :(

**Comment by Emantor** [comment]
This string will have to be made configurable like in the bareboxdriver.py (see commit a760474370d8759bea5141d00a7ed1690a1c5a0a). Do you want to submit a PR?
