### ISSUE TITLE
The authenticity of host can't be established.

### ISSUE THREAD

**Issue by kjeldflarup** [labgrid-project/labgrid#190]
When running labgrid from a docker container SSHDriver asks for this. If no operator, then the test fails.
```
The authenticity of host '172.29.1.25 (172.29.1.25)' can't be established.
ECDSA key fingerprint is 4b:6e:2e:f5:21:46:26:f5:7a:d9:9c:69:01:43:ec:d0.
Are you sure you want to continue connecting (yes/no)?
```
I patched my way around by adding -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no in sshdriver.py a number of places.

**Comment by Emantor** [comment]
Can you provide a simple example? We do exactly the same in the `_start_own_master` function in the SSHDriver which establishes the connection and uses this Socket throughout the communication with the board.

**Comment by kjeldflarup** [comment]
Maybe the controlpath is the problem, ill look into how that works. 
I do a reboot during the test. I like to do reboots in my tests.

**Comment by Emantor** [comment]
Reboots will only work if you disable the SSHDriver after the reboot, are you using a strategy for rebooting?

**Comment by kjeldflarup** [comment]
I got a fixture
```
@pytest.fixture(scope="function")
def resetshells(target):
    shell = target.get_driver('ShellDriver')
    shell.on_deactivate()
    shell.on_activate()
    shell = target.get_driver('SSHDriver')
    shell.on_deactivate()
    shell.on_activate()
```
I had commented out the SSH driver reset, because It apparently didn't have any effect, and I wasn't aware of the usage of multiplexing. When my own user knows about the fingerprint of the target, then the run command still works if the control path is lost.
