### ISSUE TITLE
SSHDriver pytest environment variables.

### ISSUE THREAD

**Issue by lion24** [labgrid-project/labgrid#216]
Hi Community :)

I also post this message on the IRC channel...

I'm really new to labgrid so please be kind :D I have successfully run my first pytest to a board connected via SSH (SSHDriver, hence no serial).
Now I want to test something more complicated, I need to run a ash script which uses environment variables to execute different type of test. I have really no clue on what is the best way to pass out these environment variables.. Ideally these env variable should be reused among the differents tests I need to execute... Thanks for the support ! :)

**Comment by Emantor** [comment]
Talked about the issue on IRC. The question was more about pytest than labgrid. :+1:
