### ISSUE TITLE
Logo for labgrid

### ISSUE THREAD

**Issue by blinry** [labgrid-project/labgrid#266]
I heard labgrid needs a pretty logo :) Here are some rough sketches around one idea. What do you think? Is this a good direction? Which one do you like best? The logos on the left are logos of other Pengutronix projects, so you can see how the new one would fit in.

![labgrid-logo](https://user-images.githubusercontent.com/81277/41318272-054401f6-6e98-11e8-940f-ea85e986fa2b.png)

Note that this is not the final font. Can you find out which font was used for the other logos?

**Comment by rohieb** [comment]
The font in the logos is [Khand](https://fonts.google.com/specimen/Khand), but it seems the serifs for the uppercase i were customized.

**Comment by blinry** [comment]
I got offline feedback that the Erlenmeyer flask doesn't seem like a good fit for a technical project. ;) Any other ideas which come to mind when thinking of a *digital* lab? Generally speaking, would you prefer a logo which resembles some concrete object, or maybe a purely abstract one?

**Comment by GOMSPACEMartin** [comment]
@blinry a 'pcb layout style' icon combined with some kind of grid perhaps?
![image](https://user-images.githubusercontent.com/34163567/44344631-6fefcd80-a491-11e8-8340-919cfe1c20f3.png) 
![image](https://user-images.githubusercontent.com/34163567/44344773-ce1cb080-a491-11e8-869f-07f69df563eb.png)

**Comment by kjeldflarup** [comment]
Four chips in a grid? The challenge is that logo's sometimes are scaled down.

**Comment by blinry** [comment]
After working on this issue with Pengutronix folks today, we built and decided on this logo:

![screenshot-2019-03-19_12:15:58](https://user-images.githubusercontent.com/81277/54602035-d0071c00-4a40-11e9-8b9f-a01596d0c953.png)
