### ISSUE TITLE
No cleanup after ManagedFiles

### ISSUE THREAD

**Issue by BastianStender** [labgrid-project/labgrid#349]
PR #308 added ManagedFiles. This enables labgrid to synchronize files (e.g. BSP artifacts) to a remote host. But file cleanup in /tmp/labgrid-{user}/{hash}/ afterwards is missing.

**Comment by jluebbe** [comment]
This behavior is intentional to allow reusing the uploads on subsequent calls (for example with labgrid-client bootstrap/fastboot flash). The documentation recommends using a regular cleanup task:
https://labgrid.readthedocs.io/en/latest/getting_started.html#exporter

**Comment by Emantor** [comment]
Hm, the documentation is not exactly correct there.
