### ISSUE TITLE
Update Managedfile upload location to /var/cache/labgrid/ and update documentation

### ISSUE THREAD

**Issue by Emantor** [labgrid-project/labgrid#350]
The directory currently is`/tmp/labgrid-$USER`.
As @ukleinek suggested below, this should be changed to `/var/cache/labgrid`.
This will require user intervention to create the folder with the correct permissions and should be made clear in the documentation and in the code which tries to access the folder.
The documentation should be fixed and contain an example tmpfiles cleanup entry and cron job.

**Comment by ukleinek** [comment]
From an administrator's POV I'd prefer if the location was e.g. `/var/cache/labgrid` as `/tmp` is not supposed to hold big files. (Consider it being a small tmpfs that occupies RAM for little gain.) So maybe it's sensible to think about moving the cache location before adapting the documentation to the current situation.

**Comment by Emantor** [comment]
The exporter should also check that the `/var/cache/labgrid` directory exists.

**Comment by rohieb** [comment]
Could portability be a problem here? Can it be ensured that the exporter does not run a non-FHS tool like e.g. Windows?
