### ISSUE TITLE
Priorities in ShellDriver and UBootDriver

### ISSUE THREAD

**Issue by bgermann** [labgrid-project/labgrid#403]
When you configure a UBootStrategy just with the necessary drivers (ShellDriver and UBootDriver) you end up with

> multiple drivers matching <class 'labgrid.protocol.commandprotocol.CommandProtocol'> found in target Target(...) with the same priorities

Please add the priorities field in at least one of the drivers.

**Comment by Emantor** [comment]
Looking at the strategy, either one of the drivers should be activated by the strategy and is than chosen over the other. Can you create a minimal working example?

**Comment by bgermann** [comment]
Okay, this is only on target.get_driver('CommandProtocol') in a test.
