### ISSUE TITLE
Xmodem executables autodetection fails

### ISSUE THREAD

**Issue by bgermann** [labgrid-project/labgrid#405]
commit 7521f159250 added XMODEM support for ShellDriver.
Some systems (checked for Debian, Arch Linux, FreeBSD) rename the original lrzsz executable file names in their packages (removing the leading l) so that lrz and lsz are not available. rx is then wrongly detected as Busybox's rx and called with wrong arguments.

Checking for [l]sz respectively [l]rz and then for rx as Busybox version should do the trick for most systems.

**Comment by Emantor** [comment]
Sounds like a good solution to the problem.
