### ISSUE TITLE
Target attributes for tests

### ISSUE THREAD

**Issue by Bastian-Krause** [labgrid-project/labgrid#422]
I came across a use case with multiple boards sharing a test suite (or at least a part of a test suite). A lot of tests can be written in a generic way, but some require a parameter, e.g. expected memory size (defined per board).
To overcome this I added these "target attributes" as a key value store in the [options yaml section](https://labgrid.readthedocs.io/en/latest/man/device-config.html#options). But this is not ideal, because "options" are apply to the whole config (not target specific). Having multiple boards described in one config renders this hack impossible. Also Config.get_option() returns all values as strings, but I'd like to get the type as the yaml parser returns them (strings, lists, ..).

This is somewhat comparable to [feature flags](#299), but "target attributes" need a key value store, not just boolean flags.

**Comment by jluebbe** [comment]
Yes, this is useful. It should also be possible to get these attributes (or tags) from the place configuration on the coordinator.

**Comment by kjeldflarup** [comment]
I have many times thought of adding something like this by cloning the NetworkService. Difference would be that the attributes are dynamical. 
```
  NetworkService:
    address: '172.29.5.35'
```

**Comment by Emantor** [comment]
Wil be fixed by #490

**Comment by Emantor** [comment]
Was fixed by #490
