### ISSUE TITLE
labgrid-client console doesn't disconnect if someone else used release --kick and acquire

### ISSUE THREAD

**Issue by spark5** [labgrid-project/labgrid#449]
Issue: If I lock a place and grab labgrid-client console, but someone else kicks me and acquires the place, I can still watch the uart output until I quit labgrid-client console.

**Comment by Emantor** [comment]
This is a known problem, however the solution requires the implementation of remote resource reservations for the exporter. This way the remote resources can be locked together with the target and connections and resources can be released correctly when the locked status changes.

**Comment by spark5** [comment]
When are you planning to implement the solution?

**Comment by Emantor** [comment]
When we find the time or necessity for the feature.
