### ISSUE TITLE
NetworkPowerPort should accept user and password for PDUs

### ISSUE THREAD

**Issue by spark5** [labgrid-project/labgrid#464]
In case of a PDU = Power Distribution Unit, like EG-PMS2-LAN or DLI Web Power Switch, a custom user and password can be configured.

**Comment by Emantor** [comment]
Depending on the security level required, a new power backend can be added and the parameters could be supplied by the YAML environment file.

**Comment by jluebbe** [comment]
I'd prefer to handle new power controllers via https://github.com/pdudaemon/pdudaemon

**Comment by spark5** [comment]
Ok. Then, are you willing to add another power driver in labgrid?

**Comment by jluebbe** [comment]
We'd take a PR to add pdudaemon support. It's been on my list for some time, but more urgent stuff keeps coming up. If you're interested, I could sketch the resource and driver structure.

**Comment by spark5** [comment]
Yes, I'm interested.

**Comment by sephalon** [comment]
Has anybody started with PDUDaemon support yet? We also need support for two different new PDUs and I probably could spend some time working on this.

**Comment by Emantor** [comment]
See #510, pdudaemon should already be working.

**Comment by sephalon** [comment]
Great, somehow I missed that…

**Comment by Emantor** [comment]
PDUDaemon is the recommended way here.
