### ISSUE TITLE
RemotePlaceManager does not receive updates if used via client with -c and -s

### ISSUE THREAD

**Issue by Emantor** [labgrid-project/labgrid#472]
The `RemotePlaceManager` can't correctly await resources using an explicit `await_resources` call when used with the state and config parameter. This results in the client waiting until the timeout is reached but not receiving updates to advance the possible strategy state. I suspect this has something to do with the reuse of the event loop within the `RemotePlaceManager` from the client. We should probably add an option for the client to pass the session instead of creating a secondary session for the `RemotePlaceManager`

**Comment by jluebbe** [comment]
This is broken since 19757a18ae39313c97e24119f9a07abd4679f27c, when I made the console command in labgrid-client async. It calls into the synchronous API via `self._get_target()`, so it can't get notified of any resource changes.
