### ISSUE TITLE
Question about labgrid-exporter.

### ISSUE THREAD

**Issue by atline** [labgrid-project/labgrid#599]
Suppose I have next remote.yaml which I will use `labgrid-exporter remote.yaml` to export:

```
example-group:
  location: example-location
  NetworkSerialPort:
    host: "192.168.1.8"
    port: 7001
example-group2:
  location: example-location2
  NetworkSerialPort:
    host: "192.168.1.8"
    port: 7002
```

My question is: if I want to add new device, should I have to stop the exporter & add to `remote.yaml` and then re-execute `labgrid-exporter remote.yaml`?

In case there is test running on existed device, if possible to not affect running one, just export new one?

I tried to write 2 `remote.yaml`, and export twice, but it told me next, looks like I can't run `labgrid-exporter` with 2 instances?

```
2020-04-09T13:32:16 Task exception was never retrieved
future: <Task finished coro=<ExporterSession.onJoin() done, defined at /root/crossbar_venv/lib/python3.6/site-packages/labgrid-0.2.1.dev422+g6837b5b-py3.6.egg/labgrid/remote/exporter.py:459> exception=ApplicationError("register for already registered procedure 'org.labgrid.exporter.pie.acquire'",)>
Traceback (most recent call last):
  File "/root/crossbar_venv/lib/python3.6/site-packages/labgrid-0.2.1.dev422+g6837b5b-py3.6.egg/labgrid/remote/exporter.py", line 467, in onJoin
    await self.register(self.acquire, '{}.acquire'.format(prefix))
autobahn.wamp.exception.ApplicationError: ApplicationError(error=<wamp.error.procedure_already_exists>, args=["register for already registered procedure 'org.labgrid.exporter.pie.acquire'"], kwargs={}, enc_algo=None, callee=None, callee_authid=None, callee_authrole=None, forward_for=None)
```

Any suggestion?

**Comment by Emantor** [comment]
> Suppose I have next remote.yaml which I will use `labgrid-exporter remote.yaml` to export:
> 
> ```
> example-group:
>   location: example-location
>   NetworkSerialPort:
>     host: "192.168.1.8"
>     port: 7001
> example-group2:
>   location: example-location2
>   NetworkSerialPort:
>     host: "192.168.1.8"
>     port: 7002
> ```
> 
> My question is: if I want to add new device, should I have to stop the exporter & add to `remote.yaml` and then re-execute `labgrid-exporter remote.yaml`?

At the exporter, you can only add resources, i.e. serial ports, IO-Ports, etc. The complete device is assembled as a place within the coordinator. Subsequently you can define all possibly connected resources in your exporter, which can be done using the jinja templating contained therein.
As an example, here is the configuration for a power-switchable USB-hub on my desk, which exports the individual ports as switchable power ports and all possible connected resources for each port
```
{% for idx, sysfs, power_index in [
        ('1', 'pci-0000:00:14.0-usb-0:3.1', '1'),
        ('2', 'pci-0000:00:14.0-usb-0:3.2', '2'),
        ('3', 'pci-0000:00:14.0-usb-0:3.3', '3'),
        ('4', 'pci-0000:00:14.0-usb-0:3.4.1', '1'),
        ('5', 'pci-0000:00:14.0-usb-0:3.4.2', '2'),
        ('6', 'pci-0000:00:14.0-usb-0:3.4.3', '3'),
        ('7', 'pci-0000:00:14.0-usb-0:3.4.4', '4')] %}

# Support for devices with multiple serial ports on one USB connection, i.e. i.MX8MQ-EVK
{% for if in [ '1.0', '1.1', '1.2', '1.3'] %}
dollysisters-dlink-7-p{{idx}}-{{if}}:
  location: "7 Port Hub auf dem Schreibtisch"
  USBSerialPort:
    match:
      '@ID_PATH': '{{sysfs}}:{{if}}'
{% endfor %}

dollysisters-dlink-7-p{{idx}}:
  location: "7 Port Hub auf dem Schreibtisch"
  IMXUSBLoader:
    match:
        'ID_PATH': '{{sysfs}}{{if}}'
  AndroidFastboot:
    match:
        'ID_PATH': '{{sysfs}}{{if}}'
  USBSDMuxDevice:
    match:
        '@ID_PATH': '{{sysfs}}{{if}}'
  USBPowerPort:
    match:
  {% if idx|int < 4 %}
      'ID_PATH': 'pci-0000:00:14.0-usb-0:3:1.0'
  {% else %}
      'ID_PATH': 'pci-0000:00:14.0-usb-0:3.4:1.0'
  {% endif %}
    index: {{power_index}}
{% endfor %}

dollysisters-cam:
  location: "Webcam über dem Remotelab"
  USBVideo:
    match:
        'ID_PATH': 'pci-0000:00:14.0-usb-0:4:1.0'
```

The `labgrid-suggest` tool can be used to generate entries for the YAML file, however templating needs to be done by the user.

> In case there is test running on existed device, if possible to not affect running one, just export new one?

Exporter restarts will abort tests which run over the same exporter.

> I tried to write 2 `remote.yaml`, and export twice, but it told me next, looks like I can't run `labgrid-exporter` with 2 instances?

Labgrid supports only one exporter per computer.
