### ISSUE TITLE
Example of actually using group.addoption would be good

### ISSUE THREAD

**Issue by mbanders** [labgrid-project/labgrid#601]
In the documentation file https://docs.pytest.org/en/latest/writing_plugins.html there is a section where this is done:

```py
def pytest_addoption(parser):
    group = parser.getgroup("helloworld")
    group.addoption(
        "--name",
        action="store",
        dest="name",
        default="World",
        help='Default "name" for hello().',
    )
```

That's good, but the example of running `pytest` below it doesn't actually use that option. This would be useful to see because what if other plugins specify `--name` options? How does a user run `pytest` and specify which option group they're in and pass in a `--name`?

Another way to ask is: Where else does the string "helloworld" have to show up?

**Comment by Emantor** [comment]
This looks to be a pytest issue, not a labgrid issue. Did you choose the wrong repository by chance?
