### ISSUE TITLE
Establish SSH-Connection in PyTest-File

### ISSUE THREAD

**Issue by mprestel** [labgrid-project/labgrid#612]
I need to connect/close one SSH-connection in a PyTest-File multiple times, but I don't know how to.

Below is my local.yaml and a simple whoami-Test to connect one time via SSH to my testboard. It works :
**local.yaml:**

targets:
  main:
    resources:
      NetworkService:
        address: '10.42.0.194'
        username: 'christ'
        password: 'christ'
    drivers:
      SSHDriver: {}

**whoami_test.py :**

def test_user(command):
    stdout, stderr, returncode = command.run('whoami')
    assert returncode == 0
    assert stdout
    assert 'christ' in stdout[0]

What commands do i need to establish/close the SSH-connection in whoami_test.py without using local.yaml ?

Many thanks and keep healthy !

**Comment by jluebbe** [comment]
Usually, a reconnect is needed because of a state transition on the Target (due to power cycle or reboot). So the convenient approach is to use a Strategy which knows exactly when to de-/activate the SSHDriver.
