### ISSUE TITLE
sshdriver not returning stdout output

### ISSUE THREAD

**Issue by TheMeaningfulEngineer** [labgrid-project/labgrid#613]
The code which provoked was a command to read a file on a target. i.e. `cat /etc/file.json`.

I have traced down the issue in the driver and the cause is in [this particular line](https://github.com/labgrid-project/labgrid/blob/master/labgrid/driver/sshdriver.py#L165).

The return from the executed command happens correctly but is than just discarded.
Would be great to know the reasoning behind the `stdout.pop()`

**Comment by jluebbe** [comment]
Probably to be compatible to the ShellDriver, which also doesn't have an empty final line. SSHDriver should only remove the last line if it is empty.

**Comment by TheMeaningfulEngineer** [comment]
@jluebbe 
Thanks, between the lines of your comment I have read this:

> This is a bug. It should be addressed by ensuring the compatibility happens in a smarted way.

Correct?

**Comment by jluebbe** [comment]
Yes. Although the run methods are already doing some processing of the output, so it's not really intended to cover all corner cases of "downloading" files. In the medium term, we should split off a way to run commands and get the raw, unprocessed output.

**Comment by Bastian-Krause** [comment]
Should be solved by #654.
