### ISSUE TITLE
Why some special character added before and after uboot command?

### ISSUE THREAD

**Issue by atline** [labgrid-project/labgrid#618]
After run with labgrid using uboot driver (Input version command):

I re-enter into uboot to see history,  using minicom, I see next:

    => echo 'FWFI''UCBAOB'; version; echo "$?"; echo 'FWFI''UCBAOB';

Means for every command, the labgrid add some echo before & after every user defined command.

What it is? Could we remove this?

**Comment by Emantor** [comment]
This is used to identify the output from the command and parse the exit code. We have no intention of making this removable or optional, since this is required for reliable parsing and exit code retrieval.
