### ISSUE TITLE
run pytests on target

### ISSUE THREAD

**Issue by HerrMuellerluedenscheid** [labgrid-project/labgrid#688]
Hey,
We have some python software that we deploy on the target that come with pytests. I was experimenting with labgrid pytest test such as:
```
import pytest

def test_py(command):
    """Test memcopy bandwidth"""

    result = command.run_check('cd fake-test;pytest')
    assert "passed" in result.decode()
```
I was wondering if there is a more direct way to execute pytests on the target, instead of parsing output of tests and interpreting the result.
Thanks in advance!

**Comment by Emantor** [comment]
No, we support simple executions as shown on in your example, but there is no further support for parsing the output of pytest or connecting both python processes on the target and test runner to retrieve test output information. If you want to implement parsing of pytest output and contribute that back to the community, https://github.com/labgrid-project/labgridhelper is the correct project for this.
Another option is to start the remote process with junit-xml and parsing the output of this file, this should be more stable than parsing the CLI output.

**Comment by HerrMuellerluedenscheid** [comment]
@Emantor Ok, I'll try to come up with a solution for that. Thanks for info!
