### ISSUE TITLE
add a way to find out the installed version

### ISSUE THREAD

**Issue by rohieb** [labgrid-project/labgrid#714]
This was already wished for in #585, but not addressed there, and today I had the same use case. Especially when installed from a source tree, the git revision would be nice to know too. A simple `labgrid-client version` could do the trick, and I think the version is available in the setuptools metadata…?

**Comment by Emantor** [comment]
Since we still recommend the installation into a virtual environment, `pip freeze` should have the currently installed version. If you are installing labgrid from some kind of package, the package itself should have the correct version information.

**Comment by rohieb** [comment]
Ah thanks, I didn't know about `pip freeze`.
