### ISSUE TITLE
Labgrid on PyPi is very out of date and broken in modern Python3

### ISSUE THREAD

**Issue by skirkham** [labgrid-project/labgrid#779]
The version of labgrid on PyPi is version `0.1.0`, which will not run in current Python as it uses the `await` keyword as a variable name.

When attempting to install [labgridhelper](https://github.com/labgrid-project/labgridhelper) without first installing labgrid manually from code, this version will be pulled in by default.

**Comment by Emantor** [comment]
AFAICS the new python package resolver and the vastly better stability of our used libraries should make PYPI releases possible again. So I'd be in favor of releasing the current version to PYPI.

**Comment by tompreston** [comment]
Related, but happy to close that PR if updated PyPI works instead :sunglasses:

**Comment by Emantor** [comment]
I just released `v0.3.4` onto Pypi, which includes a fixed readme and should be usuable from there :+1:

**Comment by tompreston** [comment]
Great, updated labgrid fixes this too https://github.com/labgrid-project/labgridhelper/pull/13
