### ISSUE TITLE
Sysfsgpio now working first time after boot

### ISSUE THREAD

**Issue by AndreHochuliMT** [labgrid-project/labgrid#856]
Hi,

We are getting forward with our test infrastructure based on LabGrid. It is really great.

When using "labgrid-client -p place_1 io high" after the exporter running on an Phytek Segin IMX6ull Board (Debian Bulls eye)
a permission denied error is thrown. The second time its working.
![Labgrid_IO_PermissionDeniedafterBoot](https://user-images.githubusercontent.com/87759445/138682569-5068568a-2a84-40b3-9f41-313748b698ca.jpg)

We are running labgrid with a testdev user and not root, therefor we are using a udev rule to set permissions on /sys/class/gpio/gpio*. The python code is to fast when exporting the gpio the first time. The write access happens before the udev rule is applied.

We see two options to solve this:
1. Why not export the GPIO after the exporter was booted. In this case no initialization during test time is needed and the results would be more reproduceable. Is there a reason we might not see, why the GPIOs are exported when the are used the first time?
2. Create a condition with username and time out, where the access to the GPIO folder is tested.

Regards André

**Comment by Emantor** [comment]
I totally agree with 1, we should export the GPIO during exporter startup, since all the required information is already available.
