### ISSUE TITLE
ability to add custom resources/drivers to exporter/client

### ISSUE THREAD

**Issue by sessl3r** [labgrid-project/labgrid#862]
### Discussed in https://github.com/labgrid-project/labgrid/discussions/845

<div type='discussions-op-text'>

<sup>Originally posted by **sessl3r** September 28, 2021</sup>
Hi all,
we have many labgrid-configured places in our lab (thanks for the great tool!). But sometimes we have the issue that we just for one project will need some slightly changed or a very custom driver (most of the time for power).

So it is clear we can write a custom driver and or resource and bundle it into the labgrid installation eventually even need to customize the exporter etc. But is there a way to do this more flexible? Eg. I have seen for remote.yaml there is a 'imports' key. 

So what would be very good to have is a simple way to import a custom resource/driver into the labgrid-exporter for in our case power and then being able to control it from the labgrid-client. Is this possible? Any easy way you can think of to achieve such things? Would the client even need to know about the new driver?

Background is that we do not want to install new exporter/clients for every minimal change so we need some more generic way to handle it. Even if we could just call a external script to control power this would be good enough - but as far as I see the ExternalPowerDriver is not thought to be used as a exportable resource?

Regards,
Tobias</div>

**Comment by Emantor** [comment]
Let's continue this in the discussion, closing the issue.
