### ISSUE TITLE
Wheel releases of labgrid

### ISSUE THREAD

**Issue by S4mw1s3** [labgrid-project/labgrid#873]
Release 0.4.1 only has .tar.gz available on https://pypi.org/project/labgrid/0.4.1/#files, however, v0.3.4 has both a .tar.gz and a whl available: https://pypi.org/project/labgrid/0.3.4/#files

Are there any plans to release whl files in the future as well?

**Comment by Emantor** [comment]
Thats me forgetting to upload the wheels, we really should automate this into a release pipeline at some point. I just released the missing wheels, closing.

**Comment by S4mw1s3** [comment]
Thanks! :)

**Comment by Emantor** [comment]
Thanks for noticing :+1:
