### ISSUE TITLE
Check if pysnmp-mib is still required for SNMP MIB conversion

### ISSUE THREAD

**Issue by Emantor** [labgrid-project/labgrid#887]
The pypi pysnmp-mibs package (https://pypi.org/project/pysnmp-mibs/) indicated that pysnmp can do the conversion using pysmi, check if this works within labgrid and remove pysnmp-mibs if it is no longer required.

**Comment by jluebbe** [comment]
My concerns are whether this needs a writable rootfs and how this affects startup time. It seems that pre-converted MIBs would solve both.

**Comment by Emantor** [comment]
Thanks for the info. I was a bit worried since pysnmp-mibs hasn't been updated in a while, on the other hand these are just precompiled MIBs. Do you still think its worth to look into this?

**Comment by jluebbe** [comment]
These basic mibs don't change often, so as long as it's compatible with pysnmp, I'm not worried.

**Comment by Emantor** [comment]
Aye, closing this.
