### ISSUE TITLE
arm docker images

### ISSUE THREAD

**Issue by obbardc** [labgrid-project/labgrid#917]
hey!
Seems like the docker images posted to https://hub.docker.com/u/labgrid are amd64 only. Is it possible to push (at least) arm64 images too ?

**Comment by jluebbe** [comment]
They are built using https://github.com/labgrid-project/labgrid/blob/master/.github/workflows/docker.yml.

As we deploy labgrid differently (using Debian packages built via CI or via meta-labgrid), we don't really use the Docker images much and would appreciate contributions there. I'm not sure if they should be build via qemu emulation or if there is a better way. @JPEWdev might have some ideas, as he worked on the images some time ago.

**Comment by jluebbe** [comment]
Thanks.

Please note that for the exporter, you need to allow access to `/dev` and udev.

**Comment by Bastian-Krause** [comment]
Resolved by #917.
