### ISSUE TITLE
Coordinator state persistence

### ISSUE THREAD

**Issue by benjamb** [labgrid-project/labgrid#947]
As things are, restarting the coordinator will result in any locks or reservations that were being tracked to be lost (despite the fact that some of this state may have been written to disk (e.g. locks in `places.yaml`)).

While easy enough to avoid this by waiting for a period where no devices are in use, it would be ideal if I could upgrade to a new container image without causing this state to be lost entirely.

I see this topic was touched upon briefly as part of https://github.com/labgrid-project/labgrid/issues/293#issuecomment-507594892, but I'm unsure if this particular comment implies that this behaviour is by design.

**Comment by Bastian-Krause** [comment]
@benjamb Is this something you strictly need? If not, I'd like to close this.

**Comment by benjamb** [comment]
@jluebbe Thanks for your response.

@Bastian-Krause This is not strictly required at this time.

**Comment by Bastian-Krause** [comment]
Okay, I'm closing this for now. If you consider working on a solution for this in the future, please reopen this issue beforehand, so we can discuss the design.
